### ISSUE TITLE
Swift Functions don't work (ErrImagePull)

### ISSUE THREAD

**Issue by wkulhanek** [projectodd/openwhisk-openshift#29]
I installed this on a 3.9.14 OpenShift cluster and it works just fine. Except for Swift functions. I keep getting an ErrImagePull error when the pod tries to start. I tried importing the image but that didn't work either.

It is looking for image 'action-swift-3:whisky'.

What needs to be done to fix this?

**Comment by jcrossley3** [comment]
Could be related to our ImageStream use, which I reverted yesteray. Re-try and re-open if still a problem, thanks!

**Comment by wkulhanek** [comment]
Thanks @jcrossley3. Just tried it and it seems to work just fine now. :-) Now the first pod deploy takes too long to run the function. But I guess after a few invocations the image will be on all nodes and that won't be an issue anymore.
