### ISSUE TITLE
Code for Docker images 

### ISSUE THREAD

**Issue by matzew** [projectodd/openwhisk-openshift#32]
Hi,

I am not 100% sure where to find the src that's behind some of the `projectodd` images, e.g.:
* docker.io/projectodd/controller
* docker.io/projectodd/invoker

PS: I know this is not a forum, but I was not able to join the #projectodd IRC channel

**Comment by jcrossley3** [comment]
Hi @matzew. We maintain an upstream fork here: https://github.com/projectodd/incubator-openwhisk

Our release tagging convention is `<branch>-<sha>`, so the ones recently referenced in here are from the `rhdemo` branch. We don't have an IRC channel, but we're usually in the OpenWhisk slack channel.

Or an issue is fine, too. :)
