### ISSUE TITLE
Can't spin up the Pods in my cluster

### ISSUE THREAD

**Issue by Mohamed-Elsodany** [projectodd/openwhisk-openshift#35]
Hello ,
i can't spin up the pods for the project in my openshift cluster , here is the Details of Events Tab:

4:05:14 PM | Normal | Back-off | Back-off pulling image "docker-registry ip:5000/openwhiskpoc/busybox:whisky"201 times in the last 47 minutes
-- | -- | -- | --
3:30:17 PM | Warning | Failed | Error: ImagePullBackOff45 times in the last 47 minutes
3:21:09 PM | Warning | Failed | Error: ErrImagePull3 times in the last 47 minutes
3:21:09 PM | Warning | Failed | Failed to pull image "docker-registry ip:5000/openwhiskpoc/busybox:whisky": rpc error: code = 2 desc = error parsing HTTP 404 response body: json: cannot unmarshal number  into Go struct field Error.detail of type float64: "{\"errors\":[{\"code\":\"MANIFEST_UNKNOWN\",\"message\":\"manifest unknown\",\"detail\":{\"Op\":\"Get\",\"URL\":\"https://registry-1.docker.io/v2/\",\… See All3 times in the last 47 minutes

3:21:09 PM | Normal | Pulling | pulling image "docker-registry ip:5000/openwhiskpoc/busybox:whisky"

any suggestions appreciated?
Thanks

**Comment by ryannix123** [comment]
I think you have to run this, although I don't know how to run it on a non-Minishift cluster.
minishift openshift config set --patch \
    '{"admissionConfig":
        {"pluginConfig":
            {"openshift.io/ImagePolicy":
                {"configuration":
                    {"apiVersion": "v1",
                     "kind": "ImagePolicyConfig",
                     "resolveImages": "AttemptRewrite"}}}}}'

**Comment by MohamedElso** [comment]
@jcrossley3 do you have any idea about this issue i reported or how to run this config set in the cluster env. that @ryannix123 mentioned.
Thanks

**Comment by MohamedElso** [comment]
i applied it on master config file but didn't fix the issue @ryannix123 @jcrossley3

**Comment by jcrossley3** [comment]
Retry with the latest master. I reverted the ImageStream usage last night, so that `ImagePolicyConfig` patch shouldn't be necessary anymore.

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 thanks, all the pods work good except this pod alarmprovider-1624473681-zctrw , it gives >> Back-off restarting failed container,
when I do oc describe pod it doesn't give many details , Do you know the reason ? or how to track it.
Thanks

------ ------                  -------
  1h            1h              1       default-scheduler                                                                       Normal           Scheduled               Successfully assigned alarmprovider-1624473681-zctrw to node ip 
  1h            1h              1       kubelet, node ip                                               Normal           SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "alarmprovider-config"
  1h            1h              1       kubelet, node ip                                              Normal           SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "openwhisk-token-pv2xc"
  1h            1h              1       kubelet, node ip       spec.initContainers{wait-for-couchdb}   Normal           Pulling                 pulling image "busybox"
  1h            1h              1       kubelet, node ip       spec.initContainers{wait-for-couchdb}   Normal           Pulled                  Successfully pulled image "busybox"
  1h            1h              1       kubelet, node ip       spec.initContainers{wait-for-couchdb}   Normal           Created                 Created container
  1h            1h              1       kubelet, node ip     spec.initContainers{wait-for-couchdb}   Normal           Started                 Started container
  1h            1h              1       kubelet, node ip       spec.initContainers{install-alarms-catalog}      Normal          Pulling                 pulling image "projectodd/whisk_alarms:8ee5579"
  1h            1h              1       kubelet, node ip       spec.initContainers{install-alarms-catalog}      Normal          Pulled                  Successfully pulled image "projectodd/whisk_alarms:8ee5579"
  1h            1h              5       kubelet, node ip       spec.initContainers{install-alarms-catalog}      Normal          Created                 Created container
  1h            1h              5       kubelet, node ip       spec.initContainers{install-alarms-catalog}      Normal          Started                 Started container
  1h            46m             8       kubelet, node ip       spec.initContainers{install-alarms-catalog}      Normal          Pulled                  Container image "projectodd/whisk_alarms:8ee5579" already present on machine
  1h            1m              246     kubelet, node ip       spec.initContainers{install-alarms-catalog}      Warning         BackOff                 Back-off restarting failed container

Thanks

**Comment by jcrossley3** [comment]
what's the output from `oc get pod alarmprovider-1624473681-zctrw -oyaml`?

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 
=======
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"openwhiskpoc","name":"alarmprovider-1624473681","uid":"5ef66909-812d-11e8-8294-005056a70e4e","apiVersion":"extensions","resourceVersion":"53962517"}}
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      alarmprovider; cpu, memory limit for container alarmprovider; cpu, memory request
      for init container wait-for-couchdb; cpu, memory limit for init container wait-for-couchdb;
      cpu, memory request for init container install-alarms-catalog; cpu, memory limit
      for init container install-alarms-catalog'
    openshift.io/scc: restricted
    pod.alpha.kubernetes.io/init-container-statuses: '[{"name":"wait-for-couchdb","state":{"terminated":{"exitCode":0,"reason":"Completed","startedAt":"2018-07-06T15:01:13Z","finishedAt":"2018-07-06T15:01:13Z","containerID":"docker://cc218e58389cfd79732d3daeeb31864152e6d86bfe09b3484d68e65500ddc560"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/busybox:latest","imageID":"docker-pullable://docker.io/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47","containerID":"docker://cc218e58389cfd79732d3daeeb31864152e6d86bfe09b3484d68e65500ddc560"},{"name":"install-alarms-catalog","state":{"waiting":{"reason":"CrashLoopBackOff","message":"Back-off
      5m0s restarting failed container=install-alarms-catalog pod=alarmprovider-1624473681-qrkdd_openwhiskpoc(5efe6395-812d-11e8-8294-005056a70e4e)"}},"lastState":{"terminated":{"exitCode":1,"reason":"Error","startedAt":"2018-07-06T15:36:40Z","finishedAt":"2018-07-06T15:37:57Z","containerID":"docker://9cae9bd07a5972482ff8e475b43b754ce0a7e1002888673dfd56ba95c00d4464"}},"ready":false,"restartCount":8,"image":"docker.io/projectodd/whisk_alarms:8ee5579","imageID":"docker-pullable://docker.io/projectodd/whisk_alarms@sha256:523105b570612d7d2d5438a92b89f4e6bd86e70e8356dec13633dd3b5e4083b2","containerID":"docker://9cae9bd07a5972482ff8e475b43b754ce0a7e1002888673dfd56ba95c00d4464"}]'
    pod.alpha.kubernetes.io/init-containers: '[{"name":"wait-for-couchdb","image":"busybox","command":["sh","-cu","echo
      \"$COUCHDB_SERVICE_HOST\""],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"name":"openwhisk-token-xmbhf","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always","securityContext":{"capabilities":{"drop":["KILL","MKNOD","SETGID","SETUID"]},"privileged":false,"seLinuxOptions":{"level":"s0:c27,c4"},"runAsUser":1000710000}},{"name":"install-alarms-catalog","image":"projectodd/whisk_alarms:8ee5579","envFrom":[{"configMapRef":{"name":"alarmprovider"}}],"env":[{"name":"DB_HOST","value":"$(COUCHDB_SERVICE_HOST):$(COUCHDB_SERVICE_PORT_COUCHDB)"},{"name":"DB_PROTOCOL","valueFrom":{"configMapKeyRef":{"name":"db.config","key":"db_protocol"}}},{"name":"AUTH_WHISK_SYSTEM","valueFrom":{"secretKeyRef":{"name":"whisk.auth","key":"system"}}}],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"name":"alarmprovider-config","mountPath":"/alarmprovider_config"},{"name":"openwhisk-token-xmbhf","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["KILL","MKNOD","SETGID","SETUID"]},"privileged":false,"seLinuxOptions":{"level":"s0:c27,c4"},"runAsUser":1000710000}}]'
    pod.beta.kubernetes.io/init-container-statuses: '[{"name":"wait-for-couchdb","state":{"terminated":{"exitCode":0,"reason":"Completed","startedAt":"2018-07-06T15:01:13Z","finishedAt":"2018-07-06T15:01:13Z","containerID":"docker://cc218e58389cfd79732d3daeeb31864152e6d86bfe09b3484d68e65500ddc560"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/busybox:latest","imageID":"docker-pullable://docker.io/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47","containerID":"docker://cc218e58389cfd79732d3daeeb31864152e6d86bfe09b3484d68e65500ddc560"},{"name":"install-alarms-catalog","state":{"waiting":{"reason":"CrashLoopBackOff","message":"Back-off
      5m0s restarting failed container=install-alarms-catalog pod=alarmprovider-1624473681-qrkdd_openwhiskpoc(5efe6395-812d-11e8-8294-005056a70e4e)"}},"lastState":{"terminated":{"exitCode":1,"reason":"Error","startedAt":"2018-07-06T15:36:40Z","finishedAt":"2018-07-06T15:37:57Z","containerID":"docker://9cae9bd07a5972482ff8e475b43b754ce0a7e1002888673dfd56ba95c00d4464"}},"ready":false,"restartCount":8,"image":"docker.io/projectodd/whisk_alarms:8ee5579","imageID":"docker-pullable://docker.io/projectodd/whisk_alarms@sha256:523105b570612d7d2d5438a92b89f4e6bd86e70e8356dec13633dd3b5e4083b2","containerID":"docker://9cae9bd07a5972482ff8e475b43b754ce0a7e1002888673dfd56ba95c00d4464"}]'
    pod.beta.kubernetes.io/init-containers: '[{"name":"wait-for-couchdb","image":"busybox","command":["sh","-cu","echo
      \"$COUCHDB_SERVICE_HOST\""],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"name":"openwhisk-token-xmbhf","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always","securityContext":{"capabilities":{"drop":["KILL","MKNOD","SETGID","SETUID"]},"privileged":false,"seLinuxOptions":{"level":"s0:c27,c4"},"runAsUser":1000710000}},{"name":"install-alarms-catalog","image":"projectodd/whisk_alarms:8ee5579","envFrom":[{"configMapRef":{"name":"alarmprovider"}}],"env":[{"name":"DB_HOST","value":"$(COUCHDB_SERVICE_HOST):$(COUCHDB_SERVICE_PORT_COUCHDB)"},{"name":"DB_PROTOCOL","valueFrom":{"configMapKeyRef":{"name":"db.config","key":"db_protocol"}}},{"name":"AUTH_WHISK_SYSTEM","valueFrom":{"secretKeyRef":{"name":"whisk.auth","key":"system"}}}],"resources":{"limits":{"cpu":"1","memory":"1Gi"},"requests":{"cpu":"100m","memory":"256Mi"}},"volumeMounts":[{"name":"alarmprovider-config","mountPath":"/alarmprovider_config"},{"name":"openwhisk-token-xmbhf","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent","securityContext":{"capabilities":{"drop":["KILL","MKNOD","SETGID","SETUID"]},"privileged":false,"seLinuxOptions":{"level":"s0:c27,c4"},"runAsUser":1000710000}}]'
  creationTimestamp: 2018-07-06T15:00:50Z
  generateName: alarmprovider-1624473681-
  labels:
    name: alarmprovider
    pod-template-hash: "1624473681"
  name: alarmprovider-1624473681-qrkdd
  namespace: openwhiskpoc
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: alarmprovider-1624473681
    uid: 5ef66909-812d-11e8-8294-005056a70e4e
  resourceVersion: "53973472"
  selfLink: /api/v1/namespaces/openwhiskpoc/pods/alarmprovider-1624473681-qrkdd
  uid: 5efe6395-812d-11e8-8294-005056a70e4e
spec:
  containers:
  - command:
    - /bin/bash
    - -c
    - source /alarmprovider_config/env; node /alarmsTrigger/app.js
    env:
    - name: DB_HOST
      value: $(COUCHDB_SERVICE_HOST):$(COUCHDB_SERVICE_PORT_COUCHDB)
    - name: DB_PROTOCOL
      valueFrom:
        configMapKeyRef:
          key: db_protocol
          name: db.config
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: db_username
          name: db.auth
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: db_password
          name: db.auth
    envFrom:
    - configMapRef:
        name: alarmprovider
    image: openwhisk/alarmprovider:1.9.0
    imagePullPolicy: IfNotPresent
    name: alarmprovider
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000710000
      seLinuxOptions:
        level: s0:c27,c4
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /alarmprovider_config
      name: alarmprovider-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: openwhisk-token-xmbhf
      readOnly: true
  dnsPolicy: ClusterFirst
  initContainers:
  - command:
    - sh
    - -cu
    - echo "$COUCHDB_SERVICE_HOST"
    image: busybox
    imagePullPolicy: Always
    name: wait-for-couchdb
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000710000
      seLinuxOptions:
        level: s0:c27,c4
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: openwhisk-token-xmbhf
      readOnly: true
  - env:
    - name: DB_HOST
      value: $(COUCHDB_SERVICE_HOST):$(COUCHDB_SERVICE_PORT_COUCHDB)
    - name: DB_PROTOCOL
      valueFrom:
        configMapKeyRef:
          key: db_protocol
          name: db.config
    - name: AUTH_WHISK_SYSTEM
      valueFrom:
        secretKeyRef:
          key: system
          name: whisk.auth
    envFrom:
    - configMapRef:
        name: alarmprovider
    image: projectodd/whisk_alarms:8ee5579
    imagePullPolicy: IfNotPresent
    name: install-alarms-catalog
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      privileged: false
      runAsUser: 1000710000
      seLinuxOptions:
        level: s0:c27,c4
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /alarmprovider_config
      name: alarmprovider-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: openwhisk-token-xmbhf
      readOnly: true
  nodeName: node ip here
  nodeSelector:
    region: app
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000710000
    seLinuxOptions:
      level: s0:c27,c4
  serviceAccount: openwhisk
  serviceAccountName: openwhisk
  terminationGracePeriodSeconds: 30
  volumes:
  - configMap:
      defaultMode: 420
      name: alarmprovider
    name: alarmprovider-config
  - name: openwhisk-token-xmbhf
    secret:
      defaultMode: 420
      secretName: openwhisk-token-xmbhf
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-07-06T15:00:50Z
    message: 'containers with incomplete status: [install-alarms-catalog]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-07-06T15:00:50Z
    message: 'containers with unready status: [alarmprovider]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2018-07-06T15:00:50Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: openwhisk/alarmprovider:1.9.0
    imageID: ""
    lastState: {}
    name: alarmprovider
    ready: false
    restartCount: 0
    state:
      waiting:
        reason: PodInitializing
  hostIP: 172.20.164.202
  initContainerStatuses:
  - containerID: docker://cc218e58389cfd79732d3daeeb31864152e6d86bfe09b3484d68e65500ddc560
    image: docker.io/busybox:latest
    imageID: docker-pullable://docker.io/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    lastState: {}
    name: wait-for-couchdb
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://cc218e58389cfd79732d3daeeb31864152e6d86bfe09b3484d68e65500ddc560
        exitCode: 0
        finishedAt: 2018-07-06T15:01:13Z
        reason: Completed
        startedAt: 2018-07-06T15:01:13Z
  - containerID: docker://9cae9bd07a5972482ff8e475b43b754ce0a7e1002888673dfd56ba95c00d4464
    image: docker.io/projectodd/whisk_alarms:8ee5579
    imageID: docker-pullable://docker.io/projectodd/whisk_alarms@sha256:523105b570612d7d2d5438a92b89f4e6bd86e70e8356dec13633dd3b5e4083b2
    lastState:
      terminated:
        containerID: docker://9cae9bd07a5972482ff8e475b43b754ce0a7e1002888673dfd56ba95c00d4464
        exitCode: 1
        finishedAt: 2018-07-06T15:37:57Z
        reason: Error
        startedAt: 2018-07-06T15:36:40Z
    name: install-alarms-catalog
    ready: false
    restartCount: 8
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=install-alarms-catalog
          pod=alarmprovider-1624473681-qrkdd_openwhiskpoc(5efe6395-812d-11e8-8294-005056a70e4e)
        reason: CrashLoopBackOff
  phase: Pending
  podIP: ip-here
  qosClass: Burstable
  startTime: 2018-07-06T15:00:50Z

Thanks

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 and i have this status on the pod 
alarmprovider-1624473681-qrkdd                0/1       Init:CrashLoopBackOff   11         58m

Thanks for your help!

**Comment by jcrossley3** [comment]
So that's clearly showing an error with the `install-alarms-catalog` init container.

Try `oc logs alarmprovider-1624473681-zctrw -c install-alarms-catalog`

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 
Waiting for controller to be available
+ : /openwhisk
+ WSK_CLI=/openwhisk/bin/wsk
+ '[' 5 -eq 0 ']'
+ AUTH=789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY
+ EDGEHOST=http://controller:8080
+ DB_URL=http://ip:5984
+ DB_NAME=whisk_alarms_alarmservice
+ APIHOST=openwhisk-openwhiskpoc.host ip here
+ WORKERS=
+ LIMIT_CRON_FIELDS=
+ '[' -f 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY ']'
+ : http://controller:8080
+ : http://ip:5984
+ : whisk_alarms_alarmservice
+ : openwhisk-openwhiskpoc.host ip here
+++ dirname ./installCatalog.sh
++ cd .
++ pwd
+ PACKAGE_HOME=/openwhisk-package-alarms
+ export WSK_CONFIG_FILE=
+ WSK_CONFIG_FILE=
+ echo Installing Alarms package.
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY --shared yes alarms -a description 'Alarms and periodic utility' -a parameters '[ {"name":"trigger_payload", "required":false} ]' -p apihost openwhisk-openwhiskpoc.host ip here -p trigger_payload ''
Installing Alarms package.
ok: updated package alarms
+ cd action
+ '[' -e alarmFeed.zip ']'
+ cp -f alarmFeed_package.json package.json
+ zip -r alarmFeed.zip lib package.json alarm.js
  adding: lib/ (stored 0%)
  adding: lib/Database.js (deflated 81%)
  adding: lib/common.js (deflated 68%)
  adding: package.json (deflated 20%)
  adding: alarm.js (deflated 50%)
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 action update --kind nodejs:6 --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY alarms/alarm /openwhisk-package-alarms/action/alarmFeed.zip -a description 'Fire trigger when alarm occurs' -a parameters '[ {"name":"cron", "required":true}, {"name":"startDate", "required":false}, {"name":"stopDate", "required":false} ]' -a feed true
ok: updated action alarms/alarm
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 action update --kind nodejs:6 --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY alarms/once /openwhisk-package-alarms/action/alarmFeed.zip -a description 'Fire trigger once when alarm occurs' -a parameters '[ {"name":"date", "required":true}, {"name":"deleteAfterFire", "required":false} ]' -a feed true -p fireOnce true
ok: updated action alarms/once
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 action update --kind nodejs:6 --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY alarms/interval /openwhisk-package-alarms/action/alarmFeed.zip -a description 'Fire trigger at specified interval' -a parameters '[ {"name":"minutes", "required":true}, {"name":"startDate", "required":false}, {"name":"stopDate", "required":false} ]' -a feed true -p isInterval true
ok: updated action alarms/interval
+ COMMAND=' -i --apihost http://controller:8080 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY --shared no alarmsWeb     -p DB_URL http://ip:5984     -p DB_NAME whisk_alarms_alarmservice     -p apihost openwhisk-openwhiskpoc.host ip here'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:5HTkaodMdoFbopkKNGmoaj442jnI5vKoeqY5CLVpPWUaKMvvyFa3YVEaVWUktFQY --shared no alarmsWeb -p DB_URL http://ip:5984 -p DB_NAME whisk_alarms_alarmservice -p apihost openwhisk-openwhiskpoc.host ip here
ok: updated package alarmsWeb
+ cp -f alarmWeb_package.json package.json
+ npm install
npm ERR! Linux 3.10.0-693.2.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Please include the following file with any support request:
npm ERR!     /openwhisk-package-alarms/action/npm-debug.log

**Comment by jcrossley3** [comment]
I have no idea why npm would be giving that error. I see no such error on minishift. :(

**Comment by MohamedElso** [comment]
@jcrossley3 please let me know if you find a fix for it , i will do searching for the error also.
Thanks

**Comment by MohamedElso** [comment]
@jcrossley3 I put this http://registry.npmjs.org/ in" NO_PROXY= "section in docker file on master and it gives me this now 
Waiting for controller to be available
+ : /openwhisk
+ WSK_CLI=/openwhisk/bin/wsk
+ '[' 5 -eq 0 ']'
+ AUTH=789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT
+ EDGEHOST=http://controller:8080
+ DB_URL=http://ip-here:5984
+ DB_NAME=whisk_alarms_alarmservice
+ APIHOST=openwhisk-openwhiskpoc.host-address-here
+ WORKERS=
+ LIMIT_CRON_FIELDS=
+ '[' -f 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT ']'
+ : http://controller:8080
+ : http://ip-here:5984
+ : whisk_alarms_alarmservice
+ : openwhisk-openwhiskpoc.host-address-here
+++ dirname ./installCatalog.sh
++ cd .
++ pwd
+ PACKAGE_HOME=/openwhisk-package-alarms
+ export WSK_CONFIG_FILE=
+ WSK_CONFIG_FILE=
+ echo Installing Alarms package.
Installing Alarms package.
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT --shared yes alarms -a description 'Alarms and periodic utility' -a parameters '[ {"name":"trigger_payload", "required":false} ]' -p apihost openwhisk-openwhiskpoc.host-address-here -p trigger_payload ''
ok: updated package alarms
+ cd action
+ '[' -e alarmFeed.zip ']'
+ cp -f alarmFeed_package.json package.json
+ zip -r alarmFeed.zip lib package.json alarm.js
  adding: lib/ (stored 0%)
  adding: lib/Database.js (deflated 81%)
  adding: lib/common.js (deflated 68%)
  adding: package.json (deflated 20%)
  adding: alarm.js (deflated 50%)
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 action update --kind nodejs:6 --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT alarms/alarm /openwhisk-package-alarms/action/alarmFeed.zip -a description 'Fire trigger when alarm occurs' -a parameters '[ {"name":"cron", "required":true}, {"name":"startDate", "required":false}, {"name":"stopDate", "required":false} ]' -a feed true
ok: updated action alarms/alarm
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 action update --kind nodejs:6 --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT alarms/once /openwhisk-package-alarms/action/alarmFeed.zip -a description 'Fire trigger once when alarm occurs' -a parameters '[ {"name":"date", "required":true}, {"name":"deleteAfterFire", "required":false} ]' -a feed true -p fireOnce true
ok: updated action alarms/once
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 action update --kind nodejs:6 --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT alarms/interval /openwhisk-package-alarms/action/alarmFeed.zip -a description 'Fire trigger at specified interval' -a parameters '[ {"name":"minutes", "required":true}, {"name":"startDate", "required":false}, {"name":"stopDate", "required":false} ]' -a feed true -p isInterval true
ok: updated action alarms/interval
+ COMMAND=' -i --apihost http://controller:8080 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT --shared no alarmsWeb     -p DB_URL http://ip-here:5984     -p DB_NAME whisk_alarms_alarmservice     -p apihost openwhisk-openwhiskpoc.host-address-here'
+ '[' -n '' ']'
+ '[' -n '' ']'
+ /openwhisk/bin/wsk -i --apihost http://controller:8080 package update --auth 789c46b1-71f6-4ed5-8c54-816aa4f8c502:lxi7kUeOfLD8nXwl1nWOIwA6ISvkcX3okJVJFxh6e2qlSF2qNQapNuKsF5H4SRnT --shared no alarmsWeb -p DB_URL http://254.2.248.176:5984 -p DB_NAME whisk_alarms_alarmservice -p apihost openwhisk-openwhiskpoc.host-address-here
ok: updated package alarmsWeb
+ cp -f alarmWeb_package.json package.json
+ npm install
but the pod (alarmprovider)still stuck becuse of install-alarms-catalog.
Thanks

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 I was thinking about putting something " NO_PROXY= "section in docker file on master so we can skip downloading the package problem, or add some parameters to the template when deploying,or add some parameters to docker images files what do u think?
@jcrossley3 where this directory exist  , npm ERR! /openwhisk-package-alarms/action/npm-debug.log ?
look at this 
https://github.com/npm/npm/issues/8872
Thanks

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 any updates/suggestions on how to bypass this error ... thanks

**Comment by jcrossley3** [comment]
This is on a clean, recent minishift with the latest master?

**Comment by Mohamed-Elsodany** [comment]
@jcrossley3 yes i used the template that you updated 6 days ago , all goes well except the error in spinning up the pod "alarmprovider" related to npm ERR as i described in recent posts .
@bbrowning 
i am using cluster openshift with this info:
Version
OpenShift Master:
v3.7.44
Kubernetes Master:
v1.7.6+a08f5eeb62
Thanks
