### ISSUE TITLE
Nginx not resolving urls to controller

### ISSUE THREAD

**Issue by shgriffi** [projectodd/openwhisk-openshift#6]
I had an issue in my environment where nginx didn't seem to be resolving calls to the controller.  Finally we got it working by changing the nginx config map from

sed -i "s/<kubernetes_service_host>/${KUBERNETES_SERVICE_HOST}/" /tmp/nginx.conf

to

sed -i "s/<kubernetes_service_host>/$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')/" /tmp/nginx.conf

Should we make this a permanent fix?

**Comment by shgriffi** [comment]
Hi guys.  Any idea on when this can be fixed?  I ran into the issue yet again while doing a deployment.

**Comment by bbrowning** [comment]
Thanks for the reminder! We need to test this change with our templates and ensure it works in our test environments as well. If so, we can get this added by default.

**Comment by shgriffi** [comment]
Ok great, thanks!
